<?= $this->include('layouts/header') ?>
<link rel="stylesheet" href="<?=base_url('assets/css/orders.css')?>?v=20260905orders1">
<?php $groups=['PURCHASE_ORDER'=>'Purchase Order','AGREEMENT'=>'Agreement','DELIVERY'=>'Delivery','OTHER'=>'Other Documents']; ?>
<div class="page-head"><div><div class="page-kicker">Orders · Documents</div><h1 class="page-title mono"><?=esc($order['order_no'])?></h1><p class="page-subtitle">Virtual folder layout only. All uploaded files use one controlled storage location.</p></div><div class="head-actions"><a class="btn" href="<?=site_url('orders/'.$order['id'])?>">← Order</a><a class="btn primary" href="<?=site_url('orders/'.$order['id'].'/edit')?>">Edit order</a></div></div>
<?php if(session()->getFlashdata('success')): ?><div class="alert success"><?=esc(session()->getFlashdata('success'))?></div><?php endif; ?><?php if(session()->getFlashdata('error')): ?><div class="alert error"><?=esc(session()->getFlashdata('error'))?></div><?php endif; ?>
<div class="card"><div class="section-head"><div><h2 class="section-title">Upload document</h2><div class="section-meta">Maximum 15 MB. The stage is a database/UI grouping, not a server folder.</div></div></div><form method="post" enctype="multipart/form-data" action="<?=site_url('orders/'.$order['id'].'/files/upload')?>" id="file-upload-form"><?=csrf_field()?><div class="form-grid three"><div class="field"><label>Stage</label><select name="stage" required><option value="PURCHASE_ORDER">Purchase Order</option><option value="AGREEMENT">Agreement</option><option value="DELIVERY">Delivery</option><option value="OTHER">Other Documents</option></select></div><div class="field" style="grid-column:span 2"><label>File</label><input type="file" name="document" required accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.xls,.xlsx,.txt"></div></div><div class="form-actions"><button class="btn primary" type="submit" id="upload-btn">Upload file →</button></div></form></div>
<div class="file-grid"><?php foreach($groups as $key=>$label):$group=array_values(array_filter($docs,fn($d)=>$d['stage']===$key)); ?><div class="card virtual-folder-card"><div class="virtual-folder-head"><span>📁</span><strong><?=esc($label)?></strong><span class="muted"><?=count($group)?> file(s)</span></div><?php if(!$group): ?><div class="empty folder-empty"><strong>No files</strong>Upload a document into this virtual folder.</div><?php else:foreach($group as $d): ?><div class="file-row full"><span>📄</span><div class="file-main"><strong><?=esc($d['file_name'])?></strong><span class="muted"><?=number_format(((int)$d['file_size'])/1024,1)?> KB · <?=esc($d['created_at'])?> IST</span></div><div class="table-actions"><a class="btn small" href="<?=site_url('orders/file/'.$d['id'].'/download')?>">Download</a><button class="btn small danger" type="button" data-file-delete="<?=$d['id']?>" data-file-name="<?=esc($d['file_name'])?>">Delete</button></div></div><?php endforeach;endif; ?></div><?php endforeach; ?></div>
<div class="order-modal" id="file-delete-modal" hidden><div class="order-modal-box"><div class="order-modal-head"><div><div class="page-kicker">Delete file</div><h3>Delete <span id="file-name"></span>?</h3></div><button class="btn small" type="button" data-close>×</button></div><p class="muted">The document record and stored file will be removed.</p><div class="order-modal-actions"><button class="btn" type="button" data-close>Cancel</button><button class="btn danger" type="button" id="confirm-file-delete">Delete file</button></div></div></div>
<script>(function(){const m=document.getElementById('file-delete-modal'),n=document.getElementById('file-name'),c=document.getElementById('confirm-file-delete'),u=<?=json_encode(site_url('orders/file'))?>;let id=null;document.addEventListener('click',e=>{const b=e.target.closest('[data-file-delete]');if(b){id=b.dataset.fileDelete;n.textContent=b.dataset.fileName;m.hidden=false;}});document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>m.hidden=true));c.addEventListener('click',async()=>{if(!id)return;c.disabled=true;c.textContent='Deleting…';const fd=new FormData();fd.append('<?=csrf_token()?>','<?=csrf_hash()?>');const r=await fetch(u+'/'+id+'/delete',{method:'POST',body:fd,headers:{'X-Requested-With':'XMLHttpRequest','Accept':'application/json'}});const j=await r.json();if(j.ok)location.reload();else{c.disabled=false;c.textContent='Delete file';m.hidden=true;}});document.getElementById('file-upload-form').addEventListener('submit',()=>{const b=document.getElementById('upload-btn');b.disabled=true;b.textContent='Uploading…';});})();</script>
<?= $this->include('layouts/footer') ?>
