<?= $this->include('layouts/header') ?>
<link rel="stylesheet" href="<?=base_url('assets/css/orders.css')?>?v=20260905orders1">
<?php $editing=!empty($order);$action=$editing?site_url('orders/'.$order['id'].'/update'):site_url('orders/store');$rows=$items?:[['product_id'=>'','variant_id'=>'','quantity'=>'']]; ?>
<div class="page-head"><div><div class="page-kicker">Orders · <?= $editing?'Edit':'Create' ?></div><h1 class="page-title"><?= $editing?'Edit '.$order['order_no']:'Create Order' ?></h1><p class="page-subtitle">Party: <strong><?=esc($party['name'])?></strong> · <?=esc($party['party_type'])?></p></div></div>
<div class="card form-card"><form method="post" action="<?=$action?>" id="order-form"><?=csrf_field()?><input type="hidden" name="party_id" value="<?=$party['id']?>">
<div class="form-grid three"><div class="field"><label>Order date</label><input type="date" name="order_date" value="<?=esc(old('order_date',$order['order_date']??date('Y-m-d')))?>" required></div><div class="field"><label>Delivery start date</label><input type="date" name="delivery_start_date" value="<?=esc(old('delivery_start_date',$order['delivery_start_date']??''))?>"></div><div class="field"><label>Delivery end date</label><input type="date" name="delivery_end_date" value="<?=esc(old('delivery_end_date',$order['delivery_end_date']??''))?>"></div></div>
<div style="margin-top:24px"><div class="split"><div><h2 class="section-title">Order items</h2><div class="section-meta">Select the exact product variant and required quantity.</div></div><button class="btn small" type="button" id="add-order-item">+ Add item</button></div>
<div id="order-items" class="order-items">
<?php foreach($rows as $i=>$row): $pid=(int)($row['product_id']??0);$vid=(int)($row['variant_id']??0);$qty=$row['quantity']??''; ?>
<div class="order-item-row" data-item-row><div class="field"><label>Product</label><select name="product_id[]" required data-product><option value="">Select product</option><?php foreach($products as $p): ?><option value="<?=$p['id']?>" <?=$pid===(int)$p['id']?'selected':''?>><?=esc($p['code'].' · '.$p['name'].' · '.$p['unit'])?></option><?php endforeach; ?></select></div><div class="field"><label>Size / Variant</label><select name="variant_id[]" required data-variant><option value="">Select product first</option></select><div class="hint" data-help>Choose a product first.</div></div><div class="field"><label>Ordered quantity</label><input type="number" name="quantity[]" min="0.001" step="0.001" value="<?=esc($qty)?>" required placeholder="e.g. 1000"></div><button class="btn icon remove-btn" type="button" data-remove>×</button></div>
<?php endforeach; ?></div></div>
<div class="field" style="margin-top:20px"><label>Notes</label><textarea name="notes" rows="4" placeholder="Order notes, reference, special instructions…"><?=esc(old('notes',$order['notes']??''))?></textarea></div>
<div class="form-actions"><a class="btn" href="<?=site_url('orders/party/'.$party['id'])?>">Cancel</a><button class="btn primary" type="submit"><?=$editing?'Update Order':'Create Order'?> →</button></div></form></div>
<script>
(function(){const map=<?=json_encode($variantMap,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;const products=<?=json_encode($products,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;const saved=<?=json_encode(array_map(fn($r)=>(int)($r['variant_id']??0),$rows),JSON_NUMERIC_CHECK)?>;const box=document.getElementById('order-items'),template=box.firstElementChild.outerHTML;function label(v){let a=[];if(v.variant_name)a.push(v.variant_name);if(v.size_value)a.push(v.size_value+' '+(v.size_unit||''));try{const x=typeof v.attributes_json==='string'?JSON.parse(v.attributes_json||'{}'):(v.attributes_json||{});Object.entries(x||{}).forEach(([k,val])=>{if(val&&typeof val==='object'&&'value' in val)val=val.value+' '+(val.unit||'');a.push(k.replace(/[_-]/g,' ')+': '+val);});}catch(e){}return [...new Set(a.filter(Boolean))].join(' · ')||'Default variant'}function update(row,selected=''){const p=row.querySelector('[data-product]').value,v=row.querySelector('[data-variant]'),list=Object.values(map).filter(x=>String(x.product_id)===String(p)),cur=selected||v.value;v.innerHTML='<option value="">Select size / variant</option>'+list.map(x=>'<option value="'+x.id+'" '+(String(x.id)===String(cur)?'selected':'')+'>'+label(x)+'</option>').join('');row.querySelector('[data-help]').textContent=list.length?list.length+' variant'+(list.length===1?'':'s')+' available.':'No active variants for this product.'}function bind(row,sel=''){row.querySelector('[data-product]').addEventListener('change',()=>update(row));row.querySelector('[data-remove]').addEventListener('click',()=>{if(box.children.length>1)row.remove()});update(row,sel)}[...box.children].forEach((r,i)=>bind(r,saved[i]||''));document.getElementById('add-order-item').addEventListener('click',()=>{const d=document.createElement('div');d.innerHTML=template;const r=d.firstElementChild;r.querySelector('[data-product]').selectedIndex=0;r.querySelector('[data-variant]').innerHTML='<option value="">Select product first</option>';r.querySelector('input[type=number]').value='';box.appendChild(r);bind(r)});})();
</script>
<?= $this->include('layouts/footer') ?>
