<?= $this->include('layouts/header') ?>
<link rel="stylesheet" href="<?=base_url('assets/css/orders.css')?>?v=20260905orders1">
<div class="page-head"><div><div class="page-kicker">Orders · Party</div><h1 class="page-title"><?=esc($party['name'])?></h1><p class="page-subtitle"><span class="badge <?=strtolower($party['party_type'])?>"><?=esc($party['party_type'])?></span> · Latest orders first</p></div><div class="head-actions"><a class="btn" href="<?=site_url('orders')?>">← Parties</a><a class="btn primary" href="<?=site_url('orders/party/'.$party['id'].'/create')?>">+ Add Order</a></div></div>
<?php if(session()->getFlashdata('success')): ?><div class="alert success"><?=esc(session()->getFlashdata('success'))?></div><?php endif; ?><?php if(session()->getFlashdata('error')): ?><div class="alert error"><?=esc(session()->getFlashdata('error'))?></div><?php endif; ?>
<div class="card"><div class="section-head"><div><h2 class="section-title">Orders</h2><div class="section-meta"><span id="order-count"><?=number_format(count($orders))?></span> shown · latest order appears first</div></div></div>
<div class="toolbar orders-toolbar"><div class="orders-filter"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="11" cy="11" r="6"/><path d="m16 16 5 5"/></svg><input id="order-filter" value="<?=esc($q)?>" placeholder="Search order no, status or notes…" autocomplete="off"></div><select id="order-status"><option value="">All statuses</option><option value="OPEN" <?=$status==='OPEN'?'selected':''?>>Open</option><option value="PARTIAL" <?=$status==='PARTIAL'?'selected':''?>>Partial</option><option value="COMPLETED" <?=$status==='COMPLETED'?'selected':''?>>Completed</option></select><span class="ajax-loader" id="order-loader"><span></span> Loading…</span></div>
<div class="table-wrap"><table class="table order-table"><thead><tr><th>Order</th><th>Status</th><th>Delivery start</th><th>Delivery end</th><th>Ordered</th><th>Delivered</th><th>Left</th><th>Action</th></tr></thead><tbody id="order-body"><?=view('orders/_order_rows',['orders'=>$orders])?></tbody></table></div></div>
<div class="order-modal" id="delete-modal" hidden><div class="order-modal-box"><div class="order-modal-head"><div><div class="page-kicker">Delete order</div><h3>Delete <span id="delete-order-no"></span>?</h3></div><button type="button" class="btn small" data-close-delete>×</button></div><p class="muted">This removes the order, its delivery history and document records. This action cannot be undone.</p><div class="order-modal-actions"><button class="btn" type="button" data-close-delete>Cancel</button><button class="btn danger" type="button" id="confirm-delete">Delete order</button></div></div></div>
<script>
(function(){const input=document.getElementById('order-filter'),status=document.getElementById('order-status'),body=document.getElementById('order-body'),count=document.getElementById('order-count'),loader=document.getElementById('order-loader'),modal=document.getElementById('delete-modal'),no=document.getElementById('delete-order-no'),confirmBtn=document.getElementById('confirm-delete');let timer=null,deleteId=null;function load(){clearTimeout(timer);timer=setTimeout(async()=>{loader.classList.add('show');try{const u=new URL(window.location.href);u.searchParams.set('q',input.value);u.searchParams.set('status',status.value);const r=await fetch(u,{headers:{'X-Requested-With':'XMLHttpRequest','Accept':'application/json'},cache:'no-store'});const j=await r.json();if(j.ok){body.innerHTML=j.html;count.textContent=Number(j.count||0).toLocaleString();}}finally{loader.classList.remove('show');}},180)}input.addEventListener('input',load);status.addEventListener('change',load);document.addEventListener('click',e=>{const b=e.target.closest('[data-delete-order]');if(b){deleteId=b.dataset.deleteOrder;no.textContent=b.dataset.orderNo;modal.hidden=false;}});document.querySelectorAll('[data-close-delete]').forEach(b=>b.addEventListener('click',()=>modal.hidden=true));confirmBtn.addEventListener('click',async()=>{if(!deleteId)return;confirmBtn.disabled=true;confirmBtn.textContent='Deleting…';const fd=new FormData();fd.append('<?=csrf_token()?>','<?=csrf_hash()?>');try{const r=await fetch('<?=site_url('orders')?>/'+deleteId+'/delete',{method:'POST',headers:{'X-Requested-With':'XMLHttpRequest','Accept':'application/json'},body:fd});const j=await r.json();if(j.ok)window.location.href=j.redirect;else{modal.hidden=true;window.location.href=window.location.href;}}finally{confirmBtn.disabled=false;confirmBtn.textContent='Delete order';}});})();
</script>
<?= $this->include('layouts/footer') ?>
