<?= $this->include('layouts/header') ?>
<link rel="stylesheet" href="<?=base_url('assets/css/gst-validation.css')?>?v=20260906gst1">
<link rel="stylesheet" href="<?=base_url('assets/css/orders.css')?>?v=20260905orders1">
<div class="page-head"><div><div class="page-kicker">Admin only · Orders</div><h1 class="page-title">Orders Dashboard</h1><p class="page-subtitle">Parties first. Select a party to manage its latest orders, deliveries and documents.</p></div><div class="head-actions"><button class="btn primary" type="button" id="open-add-party">+ Add Party</button></div></div>
<div class="grid grid-4 orders-kpis">
 <div class="card metric"><div class="metric-top"><div class="metric-label">Total parties</div><div class="metric-icon">◉</div></div><div class="metric-value" data-stat="parties"><?=number_format($stats['parties'])?></div><div class="metric-note">Active parties</div></div>
 <div class="card metric"><div class="metric-top"><div class="metric-label">Total orders</div><div class="metric-icon">▤</div></div><div class="metric-value" data-stat="orders"><?=number_format($stats['orders'])?></div><div class="metric-note">All order records</div></div>
 <div class="card metric"><div class="metric-top"><div class="metric-label">Delivered quantity</div><div class="metric-icon">✓</div></div><div class="metric-value" data-stat="delivered"><?=number_format($stats['delivered'],3)?></div><div class="metric-note good">Across all orders</div></div>
 <div class="card metric"><div class="metric-top"><div class="metric-label">Remaining quantity</div><div class="metric-icon">↗</div></div><div class="metric-value" data-stat="remaining"><?=number_format($stats['remaining'],3)?></div><div class="metric-note warn">Still to deliver</div></div>
</div>
<div class="card party-summary"><div class="summary-pill"><span>GOV</span><strong><?=number_format($stats['gov'])?></strong></div><div class="summary-pill"><span>PRIVATE</span><strong><?=number_format($stats['private'])?></strong></div><div class="summary-pill"><span>LOCAL</span><strong><?=number_format($stats['local'])?></strong></div><div class="summary-total"><span>Total ordered</span><strong><?=number_format($stats['ordered'],3)?></strong></div></div>
<?php if(session()->getFlashdata('success')): ?><div class="alert success"><?=esc(session()->getFlashdata('success'))?></div><?php endif; ?>
<?php if(session()->getFlashdata('error')): ?><div class="alert error"><?=esc(session()->getFlashdata('error'))?></div><?php endif; ?>
<div class="card">
 <div class="section-head"><div><h2 class="section-title">Parties</h2><div class="section-meta"><span id="party-count"><?=number_format(count($parties))?></span> shown · filter updates instantly</div></div></div>
 <div class="toolbar orders-toolbar"><div class="orders-filter"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="11" cy="11" r="6"/><path d="m16 16 5 5"/></svg><input id="party-filter" value="<?=esc($q)?>" placeholder="Search party, GSTIN, state, code, contact or phone…" autocomplete="off"></div><select id="party-type"><option value="">All party types</option><option value="GOV" <?=$type==='GOV'?'selected':''?>>GOV</option><option value="PRIVATE" <?=$type==='PRIVATE'?'selected':''?>>Private</option><option value="LOCAL" <?=$type==='LOCAL'?'selected':''?>>Local</option></select><span class="ajax-loader" id="party-loader"><span></span> Loading…</span></div>
 <div class="table-wrap"><table class="table"><thead><tr><th>Type</th><th>Party</th><th>GSTIN</th><th>Contact person</th><th>Phone</th><th>State / Pincode</th><th>Orders</th><th>Action</th></tr></thead><tbody id="party-body"><?=view('orders/_party_rows',['parties'=>$parties])?></tbody></table></div>
</div>
<div class="order-modal" id="order-modal" hidden><div class="order-modal-box"><div class="order-modal-head"><div><div class="page-kicker">Confirmation</div><h3 id="order-modal-title">Are you sure?</h3></div><button type="button" class="btn small" data-modal-close>×</button></div><p id="order-modal-message" class="muted"></p><div class="order-modal-actions"><button type="button" class="btn" data-modal-close>Cancel</button><button type="button" class="btn danger" id="order-modal-confirm">Confirm</button></div></div></div>
<div class="order-modal" id="add-party-modal" hidden><div class="order-modal-box order-modal-box-wide"><div class="order-modal-head"><div><div class="page-kicker">Orders · Party master</div><h3>Add Party</h3></div><button type="button" class="btn small" data-party-modal-close>×</button></div><form method="post" action="<?=site_url('orders/party/store')?>" id="add-party-form"><?=csrf_field()?><div class="form-grid three"><div class="field"><label>Party type</label><select name="party_type" required><option value="GOV">GOV · Government of India</option><option value="PRIVATE">Private · Company</option><option value="LOCAL">Local · Vendor</option></select></div><div class="field"><label>Party name</label><input name="name" required maxlength="200" placeholder="Company / Ministry / Vendor"></div><div class="field"><label>Party code</label><input name="code" maxlength="80" placeholder="Optional internal code"></div></div><div class="form-grid three"><div class="field"><label>GSTIN</label><div class="inline-gst"><input id="gstin-input" name="gstin" maxlength="15" placeholder="15-character GSTIN" style="text-transform:uppercase"><button type="button" class="btn small" id="gst-validate-btn">Validate</button></div><div class="hint" id="gst-status">GST validation required when GSTIN is entered.</div></div><div class="field"><label>Contact person</label><input name="contact_person" maxlength="150"></div><div class="field"><label>Phone</label><input name="phone" maxlength="50"></div></div><div class="form-grid three"><div class="field"><label>Email</label><input type="email" name="email" maxlength="190"></div><div class="field"><label>State</label><input name="state" maxlength="100" placeholder="State"></div><div class="field"><label>Pincode</label><input name="pincode" maxlength="10" inputmode="numeric" placeholder="Pincode"></div></div><div class="field"><label>Address</label><textarea name="address" rows="3" placeholder="Address only (state and pincode are separate)"></textarea></div><div class="form-actions"><button type="button" class="btn" data-party-modal-close>Cancel</button><button type="submit" class="btn primary" id="save-party-btn">Save Party →</button></div></form></div></div>
<script>
(function(){const input=document.getElementById('party-filter'),type=document.getElementById('party-type'),body=document.getElementById('party-body'),count=document.getElementById('party-count'),loader=document.getElementById('party-loader');let timer=null;function load(){clearTimeout(timer);timer=setTimeout(async()=>{loader.classList.add('show');try{const u=new URL(window.location.href);u.searchParams.set('q',input.value);u.searchParams.set('type',type.value);const r=await fetch(u,{headers:{'X-Requested-With':'XMLHttpRequest','Accept':'application/json'},cache:'no-store'});const j=await r.json();if(j.ok){body.innerHTML=j.html;count.textContent=Number(j.count||0).toLocaleString();Object.entries(j.stats||{}).forEach(([k,v])=>{const el=document.querySelector('[data-stat="'+k+'"]');if(el)el.textContent=Number(v||0).toLocaleString(undefined,{maximumFractionDigits:3});});}}finally{loader.classList.remove('show');}},180)}input.addEventListener('input',load);type.addEventListener('change',load);})();
(function(){const m=document.getElementById('add-party-modal'),open=document.getElementById('open-add-party'),form=document.getElementById('add-party-form'),close=m.querySelectorAll('[data-party-modal-close]'),save=document.getElementById('save-party-btn');open.addEventListener('click',()=>{m.hidden=false;setTimeout(()=>form.querySelector('[name=name]').focus(),50)});close.forEach(b=>b.addEventListener('click',()=>m.hidden=true));m.addEventListener('click',e=>{if(e.target===m)m.hidden=true});form.addEventListener('submit',()=>{save.disabled=true;save.textContent='Saving…';});})();
</script>
<div class="gst-modal" id="gst-modal" hidden><div class="gst-modal-box"><div class="order-modal-head"><div><div class="page-kicker">GST Verification</div><h3>Enter CAPTCHA</h3></div><button type="button" class="btn small" id="gst-close">×</button></div><div class="gst-captcha-wrap"><img id="gst-captcha-image" alt="GST CAPTCHA"><button type="button" class="btn small" id="gst-refresh">↻ Refresh</button></div><input class="gst-captcha-input" id="gst-captcha" placeholder="Enter CAPTCHA" autocomplete="off"><div class="hint" id="gst-modal-status"></div><div class="form-actions"><button type="button" class="btn" id="gst-cancel">Cancel</button><button type="button" class="btn primary" id="gst-submit">Verify GSTIN</button></div></div></div><script src="<?=base_url('assets/js/gst-validation.js')?>?v=20260906gst1"></script><script>window.GST_ENDPOINTS={start:'<?=site_url('gst/start')?>',refresh:'<?=site_url('gst/refresh')?>',validate:'<?=site_url('gst/validate')?>'};window.initGstValidation({input:'#gstin-input',button:'#gst-validate-btn',status:'#gst-status',modal:'#gst-modal',image:'#gst-captcha-image',captcha:'#gst-captcha',modalStatus:'#gst-modal-status',refresh:'#gst-refresh',close:'#gst-close',cancel:'#gst-cancel',submit:'#gst-submit'});</script>
<?= $this->include('layouts/footer') ?>
