<?= $this->include('layouts/header') ?>
<link rel="stylesheet" href="<?=base_url('assets/css/gst-validation.css')?>?v=20260906gst1">
<link rel="stylesheet" href="<?=base_url('assets/css/orders.css')?>?v=20260906orders2">
<?php $editing=!empty($party);$action=$editing?site_url('orders/party/'.$party['id'].'/update'):site_url('orders/party/store'); ?>
<div class="page-head"><div><div class="page-kicker">Orders · Party master</div><h1 class="page-title"><?=$editing?'Edit Party':'Add Party'?></h1><p class="page-subtitle">Maintain the organization/vendor used by the Orders module.</p></div></div>
<div class="card form-card"><form method="post" action="<?=$action?>"><?=csrf_field()?>
<div class="form-grid three"><div class="field"><label>Party type</label><select name="party_type" required><option value="GOV" <?=old('party_type',$party['party_type']??'')==='GOV'?'selected':''?>>GOV · Government of India</option><option value="PRIVATE" <?=old('party_type',$party['party_type']??'')==='PRIVATE'?'selected':''?>>Private · Company</option><option value="LOCAL" <?=old('party_type',$party['party_type']??'')==='LOCAL'?'selected':''?>>Local · Vendor</option></select></div><div class="field"><label>Party name</label><input name="name" value="<?=esc(old('name',$party['name']??''))?>" required maxlength="200" placeholder="Company / Ministry / Vendor"></div><div class="field"><label>Party code</label><input name="code" value="<?=esc(old('code',$party['code']??''))?>" maxlength="80" placeholder="Optional internal code"></div></div>
<div class="form-grid three"><div class="field"><label>Contact person</label><input name="contact_person" value="<?=esc(old('contact_person',$party['contact_person']??''))?>" maxlength="150"></div><div class="field"><label>Phone</label><input name="phone" value="<?=esc(old('phone',$party['phone']??''))?>" maxlength="50"></div><div class="field"><label>Email</label><input type="email" name="email" value="<?=esc(old('email',$party['email']??''))?>" maxlength="190"></div></div>
<div class="form-grid three"><div class="field"><label>GSTIN</label><div class="inline-gst"><input id="gstin-input" name="gstin" value="<?=esc(old('gstin',$party['gstin']??''))?>" maxlength="15" placeholder="15-character GSTIN" style="text-transform:uppercase"><button type="button" class="btn small" id="gst-validate-btn">Validate</button></div><div class="hint" id="gst-status">GST validation required when GSTIN is entered.</div></div><div class="field"><label>State</label><input name="state" value="<?=esc(old('state',$party['state']??''))?>" maxlength="100" placeholder="State"></div><div class="field"><label>Pincode</label><input name="pincode" value="<?=esc(old('pincode',$party['pincode']??''))?>" maxlength="10" inputmode="numeric" placeholder="Pincode"></div></div>
<div class="field"><label>Address</label><textarea name="address" rows="4" placeholder="Address only (state and pincode are maintained separately)…"><?=esc(old('address',$party['address']??''))?></textarea></div>
<div class="form-actions"><a class="btn" href="<?=site_url('orders')?>">Cancel</a><button class="btn primary" type="submit">Save Party →</button></div></form></div>
<div class="gst-modal" id="gst-modal" hidden><div class="gst-modal-box"><div class="order-modal-head"><div><div class="page-kicker">GST Verification</div><h3>Enter CAPTCHA</h3></div><button type="button" class="btn small" id="gst-close">×</button></div><div class="gst-captcha-wrap"><img id="gst-captcha-image" alt="GST CAPTCHA"><button type="button" class="btn small" id="gst-refresh">↻ Refresh</button></div><input class="gst-captcha-input" id="gst-captcha" placeholder="Enter CAPTCHA" autocomplete="off"><div class="hint" id="gst-modal-status"></div><div class="form-actions"><button type="button" class="btn" id="gst-cancel">Cancel</button><button type="button" class="btn primary" id="gst-submit">Verify GSTIN</button></div></div></div><script src="<?=base_url('assets/js/gst-validation.js')?>?v=20260906gst1"></script><script>window.GST_ENDPOINTS={start:'<?=site_url('gst/start')?>',refresh:'<?=site_url('gst/refresh')?>',validate:'<?=site_url('gst/validate')?>'};window.initGstValidation({input:'#gstin-input',button:'#gst-validate-btn',status:'#gst-status',modal:'#gst-modal',image:'#gst-captcha-image',captcha:'#gst-captcha',modalStatus:'#gst-modal-status',refresh:'#gst-refresh',close:'#gst-close',cancel:'#gst-cancel',submit:'#gst-submit'});</script>
<?= $this->include('layouts/footer') ?>
