<?= $this->include('layouts/header') ?>
<link rel="stylesheet" href="<?=base_url('assets/css/orders.css')?>?v=20260905orders1">
<?php $ordered=array_sum(array_map(fn($x)=>(float)$x['quantity'],$items));$delivered=array_sum(array_map(fn($x)=>(float)$x['delivered_quantity'],$items));$remaining=max(0,$ordered-$delivered);$groups=['PURCHASE_ORDER'=>'Purchase Order','AGREEMENT'=>'Agreement','DELIVERY'=>'Delivery','OTHER'=>'Other Documents']; ?>
<div class="page-head"><div><div class="page-kicker">Order detail</div><h1 class="page-title mono"><?=esc($order['order_no'])?></h1><p class="page-subtitle"><span class="badge <?=strtolower($order['party_type'])?>"><?=esc($order['party_type'])?></span> · <?=esc($order['party_name'])?></p></div><div class="head-actions"><a class="btn" href="<?=site_url('orders/party/'.$order['party_id'])?>">← Orders</a><a class="btn" href="<?=site_url('orders/'.$order['id'].'/edit')?>">Edit</a><a class="btn" href="<?=site_url('orders/'.$order['id'].'/files')?>">Files</a></div></div>
<?php if(session()->getFlashdata('success')): ?><div class="alert success"><?=esc(session()->getFlashdata('success'))?></div><?php endif; ?><?php if(session()->getFlashdata('error')): ?><div class="alert error"><?=esc(session()->getFlashdata('error'))?></div><?php endif; ?>
<div class="grid grid-4 orders-kpis"><div class="card metric"><div class="metric-label">Ordered</div><div class="metric-value"><?=number_format($ordered,3)?></div></div><div class="card metric"><div class="metric-label">Delivered</div><div class="metric-value"><?=number_format($delivered,3)?></div></div><div class="card metric"><div class="metric-label">Remaining</div><div class="metric-value"><?=number_format($remaining,3)?></div></div><div class="card metric"><div class="metric-label">Status</div><div class="metric-value" style="font-size:22px"><span class="badge <?=strtolower($order['status'])?>"><?=esc($order['status'])?></span></div></div></div>
<div class="grid grid-2">
<div class="card"><div class="section-head"><div><h2 class="section-title">Order information</h2><div class="section-meta">All dates are shown in the application timezone (IST).</div></div></div><div class="detail-grid"><div><span>Party</span><strong><?=esc($order['party_name'])?></strong></div><div><span>Party type</span><strong><?=esc($order['party_type'])?></strong></div><div><span>GSTIN</span><strong><?=esc($order['gstin']??'—')?></strong></div><div><span>State / Pincode</span><strong><?=esc($order['state']??'—')?><?=!empty($order['pincode'])?' · '.esc($order['pincode']):''?></strong></div><div><span>Order date</span><strong><?=esc($order['order_date'])?></strong></div><div><span>Delivery start</span><strong><?=esc($order['delivery_start_date']?:'—')?></strong></div><div><span>Delivery end</span><strong><?=esc($order['delivery_end_date']?:'—')?></strong></div><div><span>Party code</span><strong><?=esc($order['party_code']?:'—')?></strong></div><div class="detail-wide"><span>Notes</span><strong><?=nl2br(esc($order['notes']?:'—'))?></strong></div></div></div>
<div class="card"><div class="section-head"><div><h2 class="section-title">Party contact</h2><div class="section-meta">Master details</div></div></div><div class="detail-grid"><div><span>Contact person</span><strong><?=esc($order['contact_person']?:'—')?></strong></div><div><span>Phone</span><strong><?=esc($order['phone']?:'—')?></strong></div><div><span>Email</span><strong><?=esc($order['email']?:'—')?></strong></div><div class="detail-wide"><span>Address</span><strong><?=nl2br(esc($order['address']?:'—'))?></strong></div></div></div>
</div>
<div class="card" style="margin-top:18px"><div class="section-head"><div><h2 class="section-title">Item-wise delivery</h2><div class="section-meta">Delivered quantity is tracked separately for every ordered variant.</div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Item</th><th>Variant</th><th>Ordered</th><th>Delivered</th><th>Remaining</th><th>Progress</th></tr></thead><tbody><?php foreach($items as $it):$pct=(float)$it['quantity']>0?min(100,((float)$it['delivered_quantity']/(float)$it['quantity'])*100):0; ?><tr><td><strong><?=esc($it['item_name'])?></strong></td><td><?=esc($it['variant_name']?:'—')?></td><td><?=number_format((float)$it['quantity'],3)?></td><td><?=number_format((float)$it['delivered_quantity'],3)?></td><td><strong><?=number_format((float)$it['remaining_quantity'],3)?></strong></td><td><div class="progress"><span style="width:<?=$pct?>%"></span></div><div class="muted" style="font-size:10px;margin-top:4px"><?=number_format($pct,1)?>%</div></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="grid grid-2" style="margin-top:18px">
<div class="card"><div class="section-head"><div><h2 class="section-title">Record delivery</h2><div class="section-meta">Add a partial or final delivery against one item.</div></div></div><form method="post" action="<?=site_url('orders/'.$order['id'].'/delivery')?>"><?=csrf_field()?><div class="field"><label>Order item</label><select name="order_item_id" required><option value="">Select item</option><?php foreach($items as $it):if((float)$it['remaining_quantity']<=0)continue; ?><option value="<?=$it['id']?>"><?=esc($it['item_name'].' · '.($it['variant_name']?:'Default').' · left '.number_format((float)$it['remaining_quantity'],3))?></option><?php endforeach; ?></select></div><div class="form-grid two"><div class="field"><label>Delivery date</label><input type="date" name="delivery_date" value="<?=date('Y-m-d')?>" required></div><div class="field"><label>Quantity</label><input type="number" name="quantity" min="0.001" step="0.001" required></div></div><div class="form-grid two"><div class="field"><label>Reference number</label><input name="reference_no" placeholder="Challan / dispatch ref"></div><div class="field"><label>Remarks</label><input name="remarks" placeholder="Optional"></div></div><div class="form-actions"><button class="btn success" type="submit">Record Delivery →</button></div></form></div>
<div class="card"><div class="section-head"><div><h2 class="section-title">Documents</h2><div class="section-meta">Virtual folder view · files are not stored in stage folders.</div></div><a class="btn small" href="<?=site_url('orders/'.$order['id'].'/files')?>">Manage files</a></div><?php foreach($groups as $key=>$label):$group=array_values(array_filter($docs,fn($d)=>$d['stage']===$key)); ?><div class="virtual-folder"><div class="virtual-folder-head"><span>📁</span><strong><?=esc($label)?></strong><span class="muted"><?=count($group)?></span></div><?php if($group):foreach($group as $d): ?><a class="file-row" href="<?=site_url('orders/file/'.$d['id'].'/download')?>"><span>📄</span><span><?=esc($d['file_name'])?></span></a><?php endforeach;else:?><div class="muted folder-empty">No files</div><?php endif; ?></div><?php endforeach; ?></div>
</div>
<?php if($deliveries): ?><div class="card" style="margin-top:18px"><div class="section-head"><div><h2 class="section-title">Delivery history</h2><div class="section-meta">Latest delivery first</div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Item</th><th>Quantity</th><th>Reference</th><th>Remarks</th><th>Action</th></tr></thead><tbody><?php foreach($deliveries as $d): ?><tr><td><?=esc($d['delivery_date'])?></td><td><?=esc($d['item_name'].' · '.($d['variant_name']?:'Default'))?></td><td><strong><?=number_format((float)$d['quantity'],3)?></strong></td><td><?=esc($d['reference_no']?:'—')?></td><td><?=esc($d['remarks']?:'—')?></td><td><button type="button" class="btn small danger" data-delivery-delete="<?=$d['id']?>">Delete</button></td></tr><?php endforeach; ?></tbody></table></div></div><?php endif; ?>
<div class="order-modal" id="delivery-delete-modal" hidden><div class="order-modal-box"><div class="order-modal-head"><div><div class="page-kicker">Delete delivery</div><h3>Remove this delivery record?</h3></div><button type="button" class="btn small" data-close>×</button></div><p class="muted">The order's delivered and remaining quantities will be recalculated.</p><div class="order-modal-actions"><button type="button" class="btn" data-close>Cancel</button><button type="button" class="btn danger" id="confirm-delivery-delete">Delete delivery</button></div></div></div>
<script>(function(){const m=document.getElementById('delivery-delete-modal'),c=document.getElementById('confirm-delivery-delete');let id=null;document.addEventListener('click',e=>{const b=e.target.closest('[data-delivery-delete]');if(b){id=b.dataset.deliveryDelete;m.hidden=false;}});document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>m.hidden=true));c.addEventListener('click',async()=>{if(!id)return;c.disabled=true;c.textContent='Deleting…';const fd=new FormData();fd.append('<?=csrf_token()?>','<?=csrf_hash()?>');const r=await fetch('<?=site_url('orders/delivery')?>/'+id+'/delete',{method:'POST',body:fd,headers:{'X-Requested-With':'XMLHttpRequest','Accept':'application/json'}});const j=await r.json();if(j.ok)location.reload();else{m.hidden=true;c.disabled=false;c.textContent='Delete delivery';}})})();</script>
<?= $this->include('layouts/footer') ?>
