<?= $this->include('layouts/header') ?>
<div class="page-head"><div><div class="page-kicker">Gate desk</div><h1 class="page-title">Manual incoming entry</h1><p class="page-subtitle">Use this when scanning or OCR is unavailable. Quantity and product size/variant are recorded separately.</p></div><div class="head-actions"><a class="btn" href="<?=site_url('security')?>">← Security desk</a></div></div>
<div class="card form-card"><div class="alert info"><strong>How it works:</strong> Quantity means the number of product units received. Size is separate; for length products choose MM or inches and the system keeps the normalized inch value for reference.</div>
<form method="post" action="<?=site_url('security/manual')?>" id="manual-form"><?=csrf_field()?><div class="form-grid three"><div class="field"><label>Reference number</label><input name="reference_no" value="<?=esc(old('reference_no'))?>"></div><div class="field"><label>Supplier / sender</label><input name="party_name" value="<?=esc(old('party_name'))?>"></div><div class="field"><label>Vehicle number</label><input name="vehicle_no" value="<?=esc(old('vehicle_no'))?>"></div></div>
<div style="margin-top:20px"><div class="split"><div><h2 class="section-title">Incoming items</h2><div class="section-meta">Example: Quantity 20 pieces, Size 1000 MM.</div></div><button type="button" class="btn small" data-add-item>+ Add item</button></div>
<div id="items"><div class="item-row" data-item-row><div class="field"><label>Product</label><select name="product_id[]" required data-product-select><option value="">Select product</option><?php foreach($products as $p): ?><option value="<?=$p['id']?>"><?=esc($p['code'].' · '.$p['name'].' · '.$p['unit'])?></option><?php endforeach; ?></select></div><div class="field"><label>Size / Variant</label><select name="variant_id[]" required data-variant-select><option value="">Select product first</option></select></div><div class="field"><label>Quantity</label><input type="number" name="quantity[]" min="0.001" step="0.001" required data-qty><div class="hint">Number of product units.</div></div><div class="item-stock" data-size-label>—</div><button class="btn icon remove-btn" type="button" data-remove-item>×</button></div></div></div></div>
<div class="field" style="margin-top:16px"><label>Remarks</label><textarea name="remarks" placeholder="Optional notes…"><?=esc(old('remarks'))?></textarea></div><div class="form-actions"><a class="btn" href="<?=site_url('security')?>">Cancel</a><button class="btn success" type="submit">Confirm manual IN →</button></div></form></div>
<script>
const variantMap=<?=json_encode($variantMap??[],JSON_UNESCAPED_UNICODE)?>;const box=document.getElementById('items');const template=box.firstElementChild.outerHTML;
function updateRow(row){const s=row.querySelector('[data-product-select]'),vs=row.querySelector('[data-variant-select]'),out=row.querySelector('[data-size-label]');const current=vs.value;const list=Object.values(variantMap).filter(v=>String(v.product_id)===String(s.value));vs.innerHTML='<option value="">Select size / variant</option>'+list.map(v=>'<option value="'+v.id+'">'+v.variant_name+(v.size_value?' · '+v.size_value+' '+v.size_unit:'')+'</option>').join('');if(list.some(v=>String(v.id)===String(current)))vs.value=current;const v=variantMap[vs.value];out.textContent=v&&v.size_value?('Size · '+Number(v.size_value).toFixed(3)+' '+v.size_unit+' / '+Number(v.size_inches).toFixed(3)+' in'):(v?'Variant selected':'—');}
function bind(row){row.querySelector('[data-remove-item]')?.addEventListener('click',()=>{if(box.children.length>1)row.remove()});row.querySelector('[data-product-select]').addEventListener('change',()=>updateRow(row));row.querySelector('[data-variant-select]').addEventListener('change',()=>updateRow(row));updateRow(row)}
[...box.children].forEach(bind);document.querySelector('[data-add-item]')?.addEventListener('click',()=>{const d=document.createElement('div');d.innerHTML=template;const r=d.firstElementChild;r.querySelectorAll('input').forEach(i=>i.value='');r.querySelector('[data-product-select]').selectedIndex=0;r.querySelector('[data-variant-select]').innerHTML='<option value="">Select product first</option>';box.appendChild(r);bind(r)});
</script>
<?= $this->include('layouts/footer') ?>
