<?= $this->include('layouts/header') ?>
<div class="page-head"><div><div class="page-kicker">Verification</div><h1 class="page-title">Review incoming document</h1><p class="page-subtitle">Correct OCR results before creating the inventory IN. Quantity and product size/variant stay separate.</p></div><div class="head-actions"><a class="btn" href="<?=site_url('security')?>">← Security desk</a></div></div>
<div class="stepper"><div class="step active"><i>✓</i> Capture</div><span class="arrow">→</span><div class="step active"><i>✓</i> Read</div><span class="arrow">→</span><div class="step active"><i>3</i> Verify</div><span class="arrow">→</span><div class="step"><i>4</i> Post IN</div></div>
<div class="grid grid-2"><div class="card"><div class="section-head"><div><h2 class="section-title">Document</h2><div class="section-meta"><?=esc($document['original_filename']??'Incoming paper')?></div></div><span class="badge <?=$document['ocr_status']==='completed'?'success':'warning'?>"><?=esc($document['ocr_status'])?></span></div><div class="card-body"><div class="doc-preview"><div><div style="font-size:26px">▧</div><div style="margin-top:6px">Original file is stored securely.</div><a class="btn small" style="margin-top:12px" href="<?=site_url('security/document/'.$document['id'])?>">Open document</a></div></div></div></div>
<div class="card form-card"><form method="post" action="<?=site_url('security/scan/'.$document['id'].'/confirm')?>" id="review-form"><?=csrf_field()?><div class="field"><label>Reference / invoice number</label><input name="reference_no" value="<?=esc(old('reference_no',$extracted['reference_no']??''))?>"></div><div class="form-grid" style="margin-top:14px"><div class="field"><label>Supplier / sender</label><input name="party_name" value="<?=esc(old('party_name',$extracted['party_name']??''))?>"></div><div class="field"><label>Vehicle number</label><input name="vehicle_no" value="<?=esc(old('vehicle_no',$extracted['vehicle_no']??''))?>"></div><div class="field"><label>Document date</label><input name="document_date" value="<?=esc(old('document_date',$extracted['document_date']??''))?>"></div><div class="field"><label>Receipt source</label><input value="Security desk" readonly></div></div>
<div style="margin-top:20px"><div class="split"><div><h2 class="section-title">Items to receive</h2><div class="section-meta">Example: 20 pcs of 1000 MM. OCR values are editable.</div></div><button class="btn small" type="button" data-add-item>+ Add item</button></div>
<div id="items"><?php $sels=old('product_id',[]);$vids=old('variant_id',[]);$qtys=old('quantity',[]);if(!is_array($sels)||!count($sels)){$sels=[''];$vids=[''];$qtys=[''];} foreach($sels as $i=>$sid): ?><div class="item-row" data-item-row><div class="field"><label>Product</label><select name="product_id[]" required data-product-select data-product-search><option value="">Select product</option><?php foreach($products as $p): ?><option value="<?=$p['id']?>" <?=((string)$sid===(string)$p['id'])?'selected':''?>><?=esc($p['code'].' · '.$p['name'].' · '.$p['unit'])?></option><?php endforeach; ?></select></div><div class="field"><label>Size / Variant</label><select name="variant_id[]" required data-variant-select><option value="">Select product first</option></select></div><div class="field"><label>Quantity</label><input type="number" name="quantity[]" min="1" step="1" value="<?=esc($qtys[$i]??'')?>" required></div><div class="item-stock" data-size-label>—</div><button class="btn icon remove-btn" type="button" data-remove-item>×</button></div><?php endforeach; ?></div></div></div>
<div class="field" style="margin-top:14px"><label>Remarks</label><textarea name="remarks" placeholder="Corrections, notes or gate remarks…"><?=esc(old('remarks'))?></textarea></div><div class="alert info" style="margin-top:15px"><strong>Final check:</strong> confirm the OCR values before posting. Quantity affects stock; size is stored separately.</div><div class="form-actions"><a class="btn" href="<?=site_url('security')?>">Cancel</a><button class="btn success" type="submit">Confirm & create IN →</button></div></form></div></div>
<?php if(!empty($extracted['raw_text'])): ?><div class="card" style="margin-top:18px"><div class="section-head"><div><h2 class="section-title">Raw OCR text</h2><div class="section-meta">Reference only — not trusted until verified.</div></div></div><div class="card-body"><div class="code-block"><?=esc($extracted['raw_text'])?></div></div></div><?php endif; ?>
<script>
function variantLabel(v){try{const o=typeof v.attributes_json==='string'?JSON.parse(v.attributes_json||'{}'):(v.attributes_json||{});const parts=Object.entries(o||{}).map(([k,val])=>{const label=k.replace(/[_-]/g,' ').replace(/\b\w/g,c=>c.toUpperCase());if(val&&typeof val==='object'&&Object.prototype.hasOwnProperty.call(val,'value'))return label+': '+val.value+(val.unit?' '+val.unit:'');return label+': '+(typeof val==='object'?JSON.stringify(val):val);});return parts.join(' · ')||v.variant_name||'Default';}catch(e){return v.variant_name||'Variant';}}

const variantMap=<?=json_encode($variantMap??[],JSON_UNESCAPED_UNICODE)?>;const box=document.getElementById('items');const template=box.firstElementChild.outerHTML;const savedVariants=<?=json_encode($vids,JSON_UNESCAPED_UNICODE)?>;
function updateRow(row,saved=''){const s=row.querySelector('[data-product-select]'),vs=row.querySelector('[data-variant-select]'),out=row.querySelector('[data-size-label]');const current=saved||vs.value;const list=Object.values(variantMap).filter(v=>String(v.product_id)===String(s.value));vs.innerHTML='<option value="">Select size / variant</option>'+list.map(v=>'<option value="'+v.id+'" '+(String(v.id)===String(current)?'selected':'')+'>'+variantLabel(v)+'</option>').join('');const v=variantMap[vs.value];out.textContent=v&&v.size_value?('Size · '+Number(v.size_value).toFixed(3)+' '+v.size_unit+' / '+Number(v.size_inches).toFixed(3)+' in'):(v?'Variant selected':'—');}
function bind(row,i=0){row.querySelector('[data-remove-item]')?.addEventListener('click',()=>{if(box.children.length>1)row.remove()});row.querySelector('[data-product-select]').addEventListener('change',()=>updateRow(row));row.querySelector('[data-variant-select]').addEventListener('change',()=>updateRow(row));updateRow(row,savedVariants[i]||'')}
[...box.children].forEach((r,i)=>bind(r,i));document.querySelector('[data-add-item]')?.addEventListener('click',()=>{const d=document.createElement('div');d.innerHTML=template;const r=d.firstElementChild;r.querySelectorAll('input').forEach(i=>i.value='');r.querySelector('[data-product-select]').selectedIndex=0;r.querySelector('[data-variant-select]').innerHTML='<option value="">Select product first</option>';box.appendChild(r);bind(r,0)});
</script>
<?= $this->include('layouts/footer') ?>
