<?= $this->include('layouts/header') ?>
<link rel="stylesheet" href="<?=base_url('assets/css/transaction-detail.css?v='.rawurlencode((string)@filemtime(FCPATH.'assets/css/transaction-detail.css')))?>">
<div class="tx-detail">
<section class="tx-hero"><div><div class="tx-kicker"><?=esc(app_t('Inventory transaction'))?></div><h1 class="tx-number"><?=esc($transaction['transaction_no'])?></h1><p class="tx-sub"><?=esc(app_t('Confirmed movement and its complete audit trail.'))?></p></div><div class="tx-actions"><?php if(($transaction['type']??'')==='OUT'&&($transaction['status']??'')==='CONFIRMED'): ?><a class="btn primary" href="<?=site_url('inventory/transactions/'.(int)$transaction['id'].'/challan')?>" target="_blank">🖨 <?=esc(app_t('Print Challan'))?></a><?php endif; ?><a class="btn" href="<?=site_url('inventory/transactions')?>">← <?=esc(app_t('Transactions'))?></a><?php if(($transaction['type']??'')==='OUT'&&($transaction['status']??'')==='CONFIRMED'): ?><button class="btn whatsapp-btn" type="button" data-whatsapp-share data-transaction-no="<?=esc($transaction['transaction_no'])?>" data-transaction-type="<?=esc($transaction['type'])?>" data-party="<?=esc($transaction['party_name'] ?? '')?>" data-reference="<?=esc($transaction['reference_no'] ?? '')?>">💬 WhatsApp</button><?php endif; ?></div></section>
<div class="tx-grid">
<section class="tx-card"><div class="tx-card-head"><h2><?=esc(app_t('Transaction details'))?></h2><span><?=esc($transaction['type'])?></span></div><div class="tx-card-body"><div class="tx-meta">
<div class="tx-meta-item"><span><?=esc(app_t('Type'))?></span><strong><?=esc($transaction['type'])?></strong></div><div class="tx-meta-item"><span><?=esc(app_t('Status'))?></span><strong><span class="tx-status <?=strtolower((string)$transaction['status'])?>"><?=esc(app_t($transaction['status']))?></span></strong></div>
<div class="tx-meta-item"><span><?=esc(app_t('Date & Time'))?></span><strong><?=esc($transaction['created_at'])?></strong></div><div class="tx-meta-item"><span><?=esc(app_t('Created by'))?></span><strong><?=esc($transaction['user_name']??'System')?></strong></div>
<div class="tx-meta-item"><span><?=esc(app_t('Reference'))?></span><strong><?=esc($transaction['reference_no']??'—')?></strong></div><div class="tx-meta-item"><span><?=esc(app_t('Party / Destination'))?></span><strong><?=esc($transaction['party_name']??'—')?></strong></div>
<div class="tx-meta-item"><span><?=esc(app_t('Vehicle'))?></span><strong><?=esc($transaction['vehicle_no']??'—')?></strong></div><div class="tx-meta-item"><span>Party GSTIN</span><strong><?=esc($transaction['party_gstin']??'—')?></strong></div><?php if(!empty($transaction['operator_name']) || !empty($transaction['machine_name']) || !empty($transaction['factory_item_name'])): ?><div class="tx-meta-item"><span>Factory Product</span><strong><?=esc($transaction['factory_item_name']??'—')?></strong></div><div class="tx-meta-item"><span>Operator Name</span><strong><?=esc($transaction['operator_name']??'—')?></strong></div><div class="tx-meta-item"><span>Machine Name</span><strong><?=esc($transaction['machine_name']??'—')?></strong></div><?php endif; ?><div class="tx-meta-item"><span><?=esc(app_t('Remarks'))?></span><strong><?=esc($transaction['remarks']??'—')?></strong></div>
</div></div></section>
<section class="tx-card"><div class="tx-card-head"><h2><?=esc(app_t('Print copies'))?></h2><span>A4</span></div><div class="tx-card-body tx-print-box"><div class="tx-print-note"><?=esc(app_t('Print the confirmed OUT challan as two copies on one page, separated by a tear/cut line.'))?></div><?php if(($transaction['type']??'')==='OUT'&&($transaction['status']??'')==='CONFIRMED'): ?><a class="btn primary" target="_blank" href="<?=site_url('inventory/transactions/'.(int)$transaction['id'].'/challan')?>">🖨 <?=esc(app_t('Open print preview'))?></a><?php endif; ?></div></section>
</div>
<section class="tx-card"><div class="tx-card-head"><h2><?=esc(app_t('Items'))?></h2><span><?=number_format(count($items))?> <?=esc(app_t('line(s)'))?></span></div><div class="tx-table-wrap"><table class="tx-table"><thead><tr><th>#</th><th><?=esc(app_t('Product'))?></th><th><?=esc(app_t('Variant / Size'))?></th><th><?=esc(app_t('Quantity'))?></th><th><?=esc(app_t('Unit'))?></th></tr></thead><tbody><?php foreach($items as $i=>$item): ?><tr><td><?=$i+1?></td><td class="tx-product"><strong><?=esc($item['name'])?></strong><small><?=esc($item['code'])?></small></td><td><?=esc($item['variant_name']??'Default')?></td><td><strong><?=esc((string)((int)$item['quantity']))?></strong></td><td><?=esc($item['unit'])?></td></tr><?php endforeach; ?></tbody></table></div></section>
</div>
<script>
(function(){var b=document.querySelector('[data-whatsapp-share]');if(!b)return;b.addEventListener('click',function(){var m='Inventory OUT Transaction\nTransaction: '+(b.dataset.transactionNo||'');if(b.dataset.party)m+='\nParty / Destination: '+b.dataset.party;if(b.dataset.reference)m+='\nReference: '+b.dataset.reference;var r=[];document.querySelectorAll('.tx-table tbody tr').forEach(function(t){var c=t.querySelectorAll('td');if(c.length>=5)r.push((c[1].innerText||'').trim()+' | '+(c[2].innerText||'').trim()+' | Qty: '+(c[3].innerText||'').trim()+' '+(c[4].innerText||'').trim())});if(r.length)m+='\n\nItems:\n'+r.map(function(x,i){return(i+1)+'. '+x}).join('\n');m+='\n\nShared from Inventory Manager';window.open('https://wa.me/?text='+encodeURIComponent(m),'_blank','noopener')})})();
</script>
<?= $this->include('layouts/footer') ?>
