<?= $this->include('layouts/header') ?>
<link rel="stylesheet" href="<?=base_url('assets/css/inventory-alignment.css')?>?v=20260903align2"><link rel="stylesheet" href="<?=base_url('assets/css/quantity-calculator.css')?>?v=20260903calc1">
<div class="page-head"><div><div class="page-kicker">Inventory movement</div><h1 class="page-title">Record <?=esc($type)?></h1><p class="page-subtitle">Quantity is the stock count. Select the exact product size/variant separately.</p></div></div>
<div class="card form-card"><form method="post" action="<?=site_url('inventory/store')?>" id="movement-form"><?=csrf_field()?><input type="hidden" name="type" value="<?=esc($type)?>">
<div class="form-grid three"><div class="field"><label>Reference number</label><input name="reference_no" value="<?=esc(old('reference_no'))?>" placeholder="Invoice / challan / issue ref"></div><div class="field"><label><?= $type==='IN'?'Supplier / sender':'Issued to / destination' ?></label><input name="party_name" value="<?=esc(old('party_name'))?>" placeholder="Name or organization"></div><div class="field"><label>Vehicle number</label><input name="vehicle_no" value="<?=esc(old('vehicle_no'))?>" placeholder="Optional"></div></div>
<div style="margin-top:22px"><div class="split"><div><h2 class="section-title">Products</h2><div class="section-meta">A single product may have unlimited variants such as 9 MM, 12 MM, 16 MM. Quantity stays separate.</div></div><button class="btn small" type="button" data-add-item>+ Add item</button></div>
<div id="items">
<?php $selectedIds=old('product_id',[]);$selectedVariants=old('variant_id',[]);$selectedQty=old('quantity',[]);if(!is_array($selectedIds)||!count($selectedIds)){$selectedIds=[''];$selectedVariants=[''];$selectedQty=[''];} foreach($selectedIds as $i=>$sid): ?>
<div class="item-row" data-item-row>
<div class="field"><label>Product</label><select name="product_id[]" required data-product-select><option value="">Select product</option><?php foreach($products as $p): ?><option value="<?=$p['id']?>" data-category="<?=esc($p['category_name'] ?? '')?>" <?=((string)$sid===(string)$p['id'])?'selected':''?>><?=esc($p['code'].' · '.$p['name'].' · '.($p['category_name'] ?? 'Uncategorized').' · '.$p['unit'])?></option><?php endforeach; ?></select></div>
<div class="field"><label>Size / Variant</label><select name="variant_id[]" required data-variant-select><option value="">Select product first</option></select><div class="hint" data-variant-help>Select a product to see its available sizes.</div></div>
<div class="field"><label>Quantity</label><input type="number" name="quantity[]" min="1" step="1" value="<?=esc($selectedQty[$i]??'')?>" placeholder="e.g. 400" required data-qty></div>
<div class="item-stock" data-stock-label><?= $type==='OUT'?'Available — select variant':'—' ?></div>
<button class="btn icon remove-btn" type="button" data-remove-item aria-label="Remove">×</button>
</div><?php endforeach; ?></div></div>
<div class="field" style="margin-top:18px"><label>Remarks</label><textarea name="remarks" placeholder="Optional notes, destination, purpose…"><?=esc(old('remarks'))?></textarea></div>
<div class="alert info" style="margin:18px 0 0"><strong>Example:</strong> Steel Rod → Variant 9 MM → Quantity 400. Another line can be Steel Rod → Variant 12 MM → Quantity 600. Product stock will show <strong>Total 1,000 pcs</strong> with the two variant balances separately.</div>
<div class="form-actions"><a class="btn" href="<?=site_url('inventory')?>">Cancel</a><button class="btn <?=$type==='IN'?'success':'primary'?>" type="submit">Confirm <?=esc($type)?> →</button></div></form></div>
<script>
function variantLabel(v){try{const o=typeof v.attributes_json==='string'?JSON.parse(v.attributes_json||'{}'):(v.attributes_json||{});const parts=Object.entries(o||{}).map(([k,val])=>{const label=k.replace(/[_-]/g,' ').replace(/\b\w/g,c=>c.toUpperCase());if(val&&typeof val==='object'&&Object.prototype.hasOwnProperty.call(val,'value'))return label+': '+val.value+(val.unit?' '+val.unit:'');return label+': '+(typeof val==='object'?JSON.stringify(val):val);});return parts.join(' · ')||v.variant_name||'Default';}catch(e){return v.variant_name||'Variant';}}

const variantMap=<?=json_encode($variantMap??[],JSON_UNESCAPED_UNICODE)?>; const variantStockMap=<?=json_encode($variantStockMap??[],JSON_NUMERIC_CHECK)?>; const type='<?=esc($type)?>'; const savedVariants=<?=json_encode(old('variant_id',[]),JSON_UNESCAPED_UNICODE)?>; const itemBox=document.getElementById('items'); const template=itemBox.firstElementChild.outerHTML;
function variantsForProduct(productId){return Object.values(variantMap).filter(v=>String(v.product_id)===String(productId));}
function updateRow(row, savedVariant=''){const ps=row.querySelector('[data-product-select]'), vs=row.querySelector('[data-variant-select]'), q=row.querySelector('[data-qty]'), stock=row.querySelector('[data-stock-label]'), help=row.querySelector('[data-variant-help]'); const list=variantsForProduct(ps.value); const current=savedVariant||vs.value; vs.innerHTML='<option value="">Select size / variant</option>'+list.map(v=>{const label=variantLabel(v);return '<option value="'+v.id+'" '+(String(v.id)===String(current)?'selected':'')+'>'+label+'</option>'}).join(''); if(!list.length){vs.innerHTML='<option value="">No variants configured</option>';help.textContent='Edit the product and add at least one variant.';}else help.textContent=list.length+' variant'+(list.length===1?'':'s')+' available.'; const v=variantMap[vs.value]; if(type==='OUT'&&v){const av=Number(variantStockMap[v.id]||0);stock.textContent='Available · '+Math.round(av).toLocaleString()+' '+(variantProductUnit(v.product_id)||'units');}else stock.textContent=v?'Selected variant':'Available — select variant';}
function variantProductUnit(pid){const p=<?=json_encode(array_reduce($products,function($carry,$p){$carry[$p['id']]=$p['unit'];return $carry;},[]),JSON_UNESCAPED_UNICODE)?>;return p[pid]||'';}
function bind(row, savedVariant=''){row.querySelector('[data-remove-item]')?.addEventListener('click',()=>{if(itemBox.children.length>1)row.remove()});row.querySelector('[data-product-select]').addEventListener('change',()=>updateRow(row));row.querySelector('[data-variant-select]').addEventListener('change',()=>updateRow(row));row.querySelector('[data-qty]').addEventListener('input',()=>updateRow(row));updateRow(row,savedVariant);}
[...itemBox.children].forEach((r,i)=>bind(r,savedVariants[i]||''));document.querySelector('[data-add-item]')?.addEventListener('click',()=>{const d=document.createElement('div');d.innerHTML=template;const r=d.firstElementChild;r.querySelectorAll('input').forEach(i=>i.value='');r.querySelector('[data-product-select]').selectedIndex=0;r.querySelector('[data-variant-select]').innerHTML='<option value="">Select product first</option>';itemBox.appendChild(r);bind(r)});
</script>
<?= $this->include('layouts/footer') ?>
