<?= $this->include('layouts/header') ?>
<div class="page-head"><div><div class="page-kicker">Catalog</div><h1 class="page-title"><?=esc($title)?></h1><p class="page-subtitle">A product can have any number of size variants. Quantity is the stock count; size identifies the variant.</p></div><div class="head-actions"><a class="btn" href="<?=site_url('products')?>">← Back to products</a></div></div>
<div class="card form-card"><form method="post" action="<?= $product ? site_url('products/'.$product['id'].'/update') : site_url('products/store') ?>" id="product-form"><?=csrf_field()?><div class="form-grid">
<div class="field"><label>Product code</label><input name="code" value="<?=esc(old('code',$product['code']??''))?>" required></div>
<div class="field"><label>Product name</label><input name="name" value="<?=esc(old('name',$product['name']??''))?>" required></div>
<div class="field"><label>Category</label><select name="category_id"><option value="">No category</option><?php foreach($categories as $c): ?><option value="<?=$c['id']?>" <?=((string)old('category_id',$product['category_id']??'')===(string)$c['id'])?'selected':''?>><?=esc($c['name'])?></option><?php endforeach; ?></select></div>
<div class="field"><label>Quantity unit</label><input name="unit" value="<?=esc(old('unit',$product['unit']??'pcs'))?>" placeholder="pcs / bag / roll / kg" required><div class="hint">This is the unit counted in stock. Size is separate.</div></div>
<div class="field"><label>Measurement type</label><select name="measurement_type" id="measurement_type" required><option value="STANDARD" <?=old('measurement_type',$product['measurement_type']??'STANDARD')==='STANDARD'?'selected':''?>>Standard quantity</option><option value="LENGTH" <?=old('measurement_type',$product['measurement_type']??'STANDARD')==='LENGTH'?'selected':''?>>Length / size variants (MM or inches)</option></select></div>
<div class="field full"><label>Description</label><textarea name="description" placeholder="Optional product notes…"><?=esc(old('description',$product['description']??''))?></textarea></div>
</div>
<div class="section-head" style="margin-top:22px"><div><h2 class="section-title">Product variants</h2><div class="section-meta">Example: total 1,000 pcs → 9 MM: 400 pcs, 12 MM: 600 pcs. Add as many variants as needed.</div></div><button class="btn small" type="button" id="add-variant">+ Add variant</button></div>
<div class="variant-table-wrap"><table class="table"><thead><tr><th>Variant / label</th><th class="size-col">Size</th><th class="size-col">Unit</th><th>Opening quantity</th><th>Minimum</th><th>Inches</th><th></th></tr></thead><tbody id="variants-body">
<?php $variantRows=$variants??[]; if(!$variantRows) $variantRows=[[]]; foreach($variantRows as $i=>$v): $v=$v?:[]; ?>
<tr data-variant-row><td><input name="variant_id[]" type="hidden" value="<?=esc($v['id']??'')?>"><input name="variant_name[]" value="<?=esc(old('variant_name.'.$i,$v['variant_name']??''))?>" placeholder="e.g. 9 MM / 12 MM / Small" required></td><td class="size-col"><input name="variant_size_value[]" type="number" step="0.000001" min="0.000001" value="<?=esc(old('variant_size_value.'.$i,$v['size_value']??''))?>" placeholder="9"></td><td class="size-col"><select name="variant_size_unit[]"><option value="MM" <?=($v['size_unit']??'MM')==='MM'?'selected':''?>>MM</option><option value="IN" <?=($v['size_unit']??'')==='IN'?'selected':''?>>Inches</option></select></td><td><input name="variant_opening[]" type="number" step="0.001" min="0" value="<?=esc(old('variant_opening.'.$i,$v['opening_quantity']??'0'))?>" required></td><td><input name="variant_minimum[]" type="number" step="0.001" min="0" value="<?=esc(old('variant_minimum.'.$i,$v['minimum_quantity']??'0'))?>"></td><td class="size-col"><span data-size-inch class="mono">—</span></td><td><button class="btn icon remove-variant" type="button">×</button></td></tr>
<?php endforeach; ?></tbody></table></div>
<div class="variant-summary"><div><span class="muted">Total opening quantity</span><strong id="variant-total">0</strong> <?=esc($product['unit']??'units')?></div><div><span class="muted">Variants</span><strong id="variant-count">0</strong></div></div>
<div class="alert info" style="margin-top:18px"><strong>How stock works:</strong> each variant has its own stock ledger. Product total is the sum of all active variants. For length products, size is normalized to inches only for comparison/conversion; quantity remains a separate count.</div>
<div class="form-actions"><a class="btn" href="<?=site_url('products')?>">Cancel</a><button class="btn primary" type="submit"><?= $product?'Update product':'Create product' ?></button></div>
</form></div>
<script>
const mt=document.getElementById('measurement_type'), body=document.getElementById('variants-body'), tpl=body.firstElementChild.outerHTML;
function updateVariantRow(row){const length=mt.value==='LENGTH';row.querySelectorAll('.size-col').forEach(e=>e.style.display=length?'':'none'); const v=row.querySelector('[name="variant_size_value[]"]'); const u=row.querySelector('[name="variant_size_unit[]"]'); const out=row.querySelector('[data-size-inch]'); if(length&&v.value){const n=Number(v.value),inch=u.value==='MM'?n/25.4:n;out.textContent=inch.toFixed(3)+' in';} else out.textContent='—';}
function updateSummary(){let total=0,count=0;body.querySelectorAll('[data-variant-row]').forEach(r=>{total+=Number(r.querySelector('[name="variant_opening[]"]').value||0);count++;updateVariantRow(r);});document.getElementById('variant-total').textContent=total.toFixed(3);document.getElementById('variant-count').textContent=count;}
function bind(r){r.querySelector('.remove-variant').onclick=()=>{if(body.children.length>1){r.remove();updateSummary()}};r.querySelectorAll('input,select').forEach(e=>e.addEventListener('input',updateSummary));r.querySelectorAll('select').forEach(e=>e.addEventListener('change',updateSummary));}
[...body.children].forEach(bind);mt.addEventListener('change',updateSummary);document.getElementById('add-variant').onclick=()=>{const d=document.createElement('tbody');d.innerHTML=tpl;const r=d.firstElementChild;r.querySelectorAll('input').forEach(i=>{if(i.name!=='variant_id[]')i.value=''});r.querySelector('[name="variant_id[]"]').value='';r.querySelector('[name="variant_size_unit[]"]').value='MM';body.appendChild(r);bind(r);updateSummary()};updateSummary();
</script><?= $this->include('layouts/footer') ?>
